#!/bin/bash

KEEP_GOING=false
TESTDIR=~/src/680x0/68000/v1

while getopts "kt:" opt; do
	case "$opt" in
		k) KEEP_GOING=true;;
		t) TESTDIR="$OPTARG";;
		*) echo "Usage: $0 [-k] [-t test-dir] [test-names...]"; exit 1;;
	esac
done

shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
	TESTS="$*"
else
	TESTS="$(ls -1 ${TESTDIR} | sed -e 's/.json.gz//')"
fi

for t in $TESTS; do
	TESTFILE=${TESTDIR}/$t.json.gz
	RESULTFILE=results/$t
	echo -n "$t: "
	if [ ! -f ${RESULTFILE} ]; then
		echo "SKIP"
	elif $(./sstests ${TESTFILE} -k | cmp -s - ${RESULTFILE}); then
		echo "PASS"
	else
		echo "FAIL"
		$KEEP_GOING || exit 1
	fi
done
